/*
 * This code has been generated by the Rebel: a code generator for modern Java.
 *
 * Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
 */
package com.cda.contenu_seance.model;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.*;
import java.util.*;

@Entity
@Getter
@Setter
@NoArgsConstructor
@DiscriminatorValue(value = "formateur")

public class Formateur extends Intervenant {
    @ManyToMany(mappedBy = "formateurs")
    private List<Session> sessions;
    @OneToMany(mappedBy = "formateur")
    private List<Seance> seances;
}
