/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.cda.contenu_seance.model;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.lang.Nullable;

import javax.persistence.*;
import java.util.*;


// ----------- << imports@AAAAAAF/IZXTBdrxFoA= >>
// ----------- >>

@Entity
@Getter
@Setter
@NoArgsConstructor

public class Seance {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Temporal(TemporalType.DATE)
    private Date dateDuJour;
    private int duree;
    private String supportUse;
    private String deroulement;
    private String objectifPeda;
    @ManyToOne
    private Formateur formateur;
    @ManyToOne
    private Session session;

    @ManyToMany(mappedBy = "seances")
    private List<Competence> competences;


}