/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.cda.contenu_seance.model;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.Hibernate;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import java.util.*;
//table associative crée avec le ManyToMany
// ManyToMany mappedBy obligatoire peu importe le sens
// OneToMany : quand j'ai une liste = pointer l'attribut de l'enfant avec mappedBy
//
@Entity
@Getter
@Setter
@NoArgsConstructor



public class Session {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Temporal(TemporalType.DATE)
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date dateDebut;

    @Temporal(TemporalType.DATE)
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date dateFin;

    @OneToMany(mappedBy = "session")
    private List<Seance> seances;
    @ManyToOne
    private Centre centre;
    @ManyToOne
    private Formation formation;
    @ManyToMany
    private List <Formateur> formateurs;
    @ManyToOne
    private Coordinateur coordinateur;


}